### Practice DFS and BFS

Background - I have a problem in my thesis, I think I need to find the largest grouping of detected area in an image. Maybe I can use DFS? So I just want a refresher.

In [1]:
import numpy as np
from dataclasses import dataclass
from typing import TypeVar

from random import randint

In [2]:
N = 10
grid = np.random.randint(2, size=(N, N))

# Don't consider diagonal, change this check criteria anytime
checks = [(0, 1), (1, 0), (0, -1), (-1, 0)]
size = 0

def valid(x: int, y: int, n: int):
    """Valid tile loc."""
    return 0 <= x and 0 <= y and x < n and y < n

def dfs(x: int, y: int, grid, visited):
    """Find island size?"""
    global size
    
    # Check only non visited and non zero vertex
    if visited[x][y] or not grid[x][y]:
          return None
    
    visited[x][y] = 1
    size += 1
    
    for _x, _y in checks:
        nx = x + _x
        ny = y + _y
        
        # Criteria for the next vertex search
        if valid(nx, ny, N) and not visited[nx][ny] and grid[nx][ny]:
            dfs(x + _x, y + _y, grid, visited)
          
    
def run_dfs():
    global size
    lookup = np.zeros((N, N), dtype=int)
    ic = 1
    
    for i in range(N):
        for j in range(N):
            dfs(i, j, grid, lookup)
            if size != 0:
                print(f"Island {ic} size: {size}")
                ic += 1
            size = 0
            
print(grid)
run_dfs()

[[0 1 1 0 1 0 1 0 0 1]
 [0 1 1 0 0 0 0 0 1 0]
 [0 1 1 1 1 1 1 0 0 0]
 [0 0 1 1 1 0 1 1 0 1]
 [0 1 0 1 0 0 1 1 1 0]
 [0 0 0 0 0 1 0 1 0 0]
 [0 0 0 0 1 0 1 1 0 0]
 [0 1 0 0 0 1 1 1 1 0]
 [1 0 1 0 1 1 0 0 1 1]
 [0 0 1 0 1 1 0 0 0 1]]
Island 1 size: 33
Island 2 size: 1
Island 3 size: 1
Island 4 size: 1
Island 5 size: 1
Island 6 size: 1
Island 7 size: 1
Island 8 size: 1
Island 9 size: 1
Island 10 size: 1
Island 11 size: 1
Island 12 size: 2


BFS - maybe search for 

In [3]:
# BFS

g = { 
    "a" : ["c","b"],
    "b" : ["e", "d"],
    "c" : ["f"],
    "d" : [],
    "e" : [],
    "f": []
}



def run_bfs(graph, start):
    """BFS."""
    
    q = []
    q.append(start)
    
    node_count = len(graph.keys())
    node_keys = list(graph.keys())
    
    parent = [None] * node_count
    visited = [False] * node_count
    visited[node_keys.index(start)] = True
    
    while q:
        current = q.pop(0)
        
        # get adjacent nodes
        adjacent = graph[current]
        
        for _adj in adjacent:
            if not visited[node_keys.index(_adj)]:
                q.append(_adj)
                # Mark as visited
                visited[node_keys.index(_adj)] = True
                # Track parent
                parent[node_keys.index(_adj)] = node_keys.index(current)
                
        print(current, end=" ")
    
    return parent

def trace(graph, parent, start, end):
    """
    Trace if connected.
    
    Args:
    parent - list containing parent of each node
    start - start node
    end - end node
    """
    node_keys = list(graph.keys())
    current = end
    
    while parent[node_keys.index(current)] is not None:
        
        current = node_keys[parent[node_keys.index(current)]]
    
    if current != start:
        return False
    
    return True

def is_connected(graph, start, end):
    """Check connectedness."""
    tr = run_bfs(g, start)
    c = trace(g, tr, start, end)
    print(c)
    

is_connected(g, "a", "c")

a c b f e d True


In [4]:
g = { 
    "a" : ["c","b"],
    "b" : ["e", "d"],
    "c" : ["f"],
    "d" : [],
    "e" : [],
    "f": []
}

# Non-recursive
def run_dfs(graph, current):
    """
    DFS.
    
    Args:
    graph - graph to traverse
    current - starting node from the graph
    """
    
    stack = []
    # Assume there will be no duplicate values for the node.
    visited = []
    
    stack.append(current)
    
    while stack:
        current = stack.pop()
        visited.append(current)
        
        # Get the adjacent nodes
        adjacent = graph[current]
        
        for _adj in adjacent:
            if _adj not in visited:
                stack.append(_adj)
        
        print(current, end=" ")
        
run_dfs(g, "a")
print()
        
        
# Recursive
global_visited = []

def dfs(node):
#     if node == None: return
    
    print(node, end=" ")
    adjacent = g[node]
    global_visited.append(node)
    
    for _adj in adjacent:
        if _adj not in global_visited:
            dfs(_adj)
    
dfs("a")

a b d e c f 
a c f b e d 

In [5]:
# Linked List

Node = TypeVar("Node")

@dataclass(slots=True)
class Node:
    value: int
    next_node: Node = None
         
class LinkedList:
    head = None
    
    def __init__(self, head: Node = None):
        self.head = head

    def traverse(self):
        """Prints linkedlist value"""
        ptr = self.head
    
        while ptr is not None:
            print(ptr.value, end=" ")
            ptr = ptr.next_node
            
    def reverse(self):
        """Reverses current linked list."""
        prev = None
        temp_next = None
        current = self.head
    
        while current is not None:
            temp_next = current.next_node
            current.next_node = prev
            prev = current
            current = temp_next
            
        self.head = prev
        
    
    def search(self, value: int = None):
        """Lookup function."""
        if value is None or type(value) != int:
            return None
        
        ptr = self.head
    
        while ptr is not None:
            if ptr.value == value:
                return value
            
            ptr = ptr.next_node
        return None
    
    def node_value(self, index: int = None) -> int:
        """Search based on index"""
        if index is None or type(index) != int:
            return None
        
        ptr = self.head
        
        while ptr is not None:
            if index == 0:
                return ptr.value
            index -= 1
            ptr = ptr.next_node
            

def recursive_traverse(head: Node):
    """Prints linked list."""
    
    if head is None: return
    print(head.value, end=" ")
    
    recursive_traverse(head.next_node)
            
            
def recursive_reverse(prev_node: Node, current_node: Node):
    """Reverse list recursive."""
    if current_node == None: return prev_node # Return new head
        
    temp_next = current_node.next_node
    current_node.next_node = prev_node

    return recursive_reverse(current_node, temp_next)
    
    
            
def recursive_get_value(head: Node, index: int) -> int:
    """Recursively returns node value at given index."""
    
    if head is None: return None
    
    if index == 0:
        return head.value
    
    return recursive_get_value(head.next_node, index - 1)

        
def recursive_search(head: Node, value: int) -> bool:
    if head is None: return False
    if head.value == value: return True

    return recursive_search(head.next_node, value)

        
def populate(n: int = 1):
    """Creates N random nodes."""
    head = Node(value=randint(1, 10))
    ptr = head
    
    for _ in range(n - 1):
        ptr.next_node = Node(value=randint(1, 10))
        ptr = ptr.next_node
        
    return head
    

ll = LinkedList(populate(10))
ll.traverse()
ll.reverse()
print()
ll.traverse()
print()
ll2 = LinkedList(populate(10))
ll2.traverse()
print()
new_head = recursive_reverse(None, ll2.head)
LinkedList(new_head).traverse()

print(ll.search(3))
print(recursive_search(ll.head, 3))

print(ll.node_value(3), ll.node_value(5))
print(recursive_get_value(ll.head, 3), recursive_get_value(ll.head, 5))

8 10 6 6 5 2 10 7 10 9 
9 10 7 10 2 5 6 6 10 8 
4 5 1 8 5 5 10 2 5 7 
7 5 2 10 5 5 8 1 5 4 None
False
10 5
10 5


In [6]:
def merge(l1: Node, l2: Node) -> Node:
    """Merge two linkelist"""
    if l2 is None and l1 is None:
        return None
    if l1 is None:
        return l2
    if l2 is None:
        return l1
    
    ptr1 = l1.next_node
    ptr2 = l2
    counter = 0
    # Tracks end of merged list
    end = l1
    
    while ptr1 is not None and ptr2 is not None:
       
        if counter % 2 == 0:
            end.next_node = ptr2
            end = ptr2
            ptr2 = ptr2.next_node
        else:
            end.next_node = ptr1
            end = ptr1
            ptr1 = ptr1.next_node
        
        counter += 1
    
    if ptr2 is None:
        end.next_node = ptr1
    if ptr1 is None:
        end.next_node = ptr2
    
    
    return l1



def merge2(l1: Node, l2: Node) -> Node:
    """Merge two linkelist"""
    if l2 is None and l1 is None: return None
    if l1 is None: return l2
    if l2 is None: return l1
    
    """
    1 2 3 4 5
    6 7 8 None
    """
    
    c1 = l1
    c2 = l2
    # Wasted
    tmp = Node(0)
    
    while c1 is not None and c2 is not None:
        
        tmp.next_node = c1
        tmp = c1
        c1 = c1.next_node
        
        tmp.next_node = c2
        tmp = c2
        c2 = c2.next_node
        
    if c1 is None:
        tmp.next_node = c2
    if c2 is None:
        tmp.next_node = c1
    
    return l1


def recursive_merge(head1: Node, head2: Node) -> Node:
    """Recursive merge."""
    if head1 is None and head2 is None: return None
    if head1 is None: return head2
    if head2 is None: return head1
    
    head2.next_node = recursive_merge(head1.next_node, head2.next_node)
    head1.next_node = head2
    
    return head1


# Merge two linked list
l1 = populate(3)
recursive_traverse(l1)
print()
l2 = populate(5)
recursive_traverse(l2)
print()

head = recursive_merge(l1, l2)
recursive_traverse(head)

2 5 4 
8 3 8 4 10 
2 8 5 3 4 8 4 10 

In [13]:
### Binary trees
Node = TypeVar("Node")

@dataclass(slots=True)
class Node:
    value: str
    left: Node = None
    right: Node = None
        

a = Node("a")
b = Node("b")
c = Node("c")
d = Node("d")
e = Node("e")
f = Node("f")
g = Node("g")
h = Node("h")
i = Node("i")

a.left = b
a.right = c
b.left = d
b.right = e
c.right = f

In [23]:
def dfs(node: Node):    
    if node == None: return []
    left = dfs(node.left)
    right = dfs(node.right)
    return ([node.value] + left + right)
    
print(dfs(a))


def bfs_iter(node: Node):
    if node is None: return None
    q = []
    q.append(node)
    vals = []
    
    while q:
        n = q.pop(0)
        vals.append(n.value)
        if n.left is not None: q.append(n.left)
        if n.right is not None: q.append(n.right)
    
    return vals
            
print(bfs_iter(a))

['a', 'b', 'd', 'e', 'c', 'f']
['a', 'b', 'c', 'd', 'e', 'f']


In [29]:
def tree_search(node: Node, target: str) -> bool:
    if node is None: return False
    q = []
    q.append(node)
    
    while q:
        n = q.pop(0)
        
        if n.value == target: return True
        
        if n.left is not None: q.append(n.left)
        if n.right is not None: q.append(n.right)
    
    return False

def tree_search_recursive(node: Node, target: str) -> bool:
    if node is None: return False
    if node.value == target: return True
    
    return tree_search_recursive(node.left, target) or tree_search_recursive(node.right, target)

_c = "h"
print(tree_search(a, _c))
print(tree_search_recursive(a, _c))

False
False


In [42]:
import math
a = Node(5)
b = Node(11)
c = Node(3)
d = Node(4)
e = Node(2)
f = Node(1)

a.left = b
a.right = c
b.left = d
b.right = e
c.right = f

def tree_sum(node: Node) -> int:
    if node is None: return 0
    return node.value + tree_sum(node.left) + tree_sum(node.right)

print(tree_sum(a))


def tree_min(node: Node) -> int:
    if node is None: return math.inf
    l = tree_min(node.left)
    r = tree_min(node.right)
    return min(node.value, l, r)


print(tree_min(a))

def tree_max_path(node: Node) -> int:
    if node is None: return -math.inf
    l = tree_max_path(node.left)
    r = tree_max_path(node.right)
    m = max(l, r)
    m = m if m != -math.inf else 0
    return m + node.value

print(tree_max_path(a))

26
1
20


In [78]:
# LRU Cache
from typing import Optional

@dataclass
class CacheNode:
    key: int            # included this for easier tracking?
    value: int
    next_node: Optional = None
    prev_node: Optional = None
    
class LRUCache:
    
    def __init__(self, n):
        self.limit = n
        self.data = dict()
        self.top = None
        self.bottom = None
        
    def get(self, key: int):
        if key not in self.data: return None
        if self.top.key != key: 
            # Do rearrange
            self._rearrange(key)
            self._insert_top(self.data[key])
        
        return self.data[key].value
    
    def put(self, key: int, value: int):
        
        # If cache is empty
        if not self.data:
            n = CacheNode(key, value)
            self.top = n
            self.bottom = n
            self.data[key] = n
            return
        
        # Upsert
        if key in self.data:
            # If key is already in data
            self.data[key].value = value
            if self.top.key == key: return # Nothing changes
            
            self._rearrange(key)
            self._insert_top(self.data[key])
        
        # Insert totally new node
        else:
            # Check size
            size = len(self.data.keys())
    
            # Cannot insert delete oldest
            if size >= self.limit:
                tmp = self.bottom
                self.bottom = self.bottom.prev_node
                self.bottom.next_node = None
                tmp.prev_node = None
                del self.data[tmp.key]
            
            n = CacheNode(key, value)
            self.data[key] = n
            self._insert_top(n)
            
    def _rearrange(self, key: int):
        # Rearranges the linked list before moving the node
        # to the top
        
        # x <-> y <-> None
        _next = self.data[key].next_node # None
        _prev = self.data[key].prev_node # x
        # x -> None
        _prev.next_node = _next
        if _next is not None:
            _next.prev_node = _prev
        else:
            self.bottom = _prev

    def _insert_top(self, new_top: CacheNode):
        # Makes sure to insert node at the top
        new_top.prev_node = None
        new_top.next_node = self.top
        self.top.prev_node = new_top
        self.top = new_top
        
    def print_linked_list(self):
        current = self.top
        while current is not None:
            print(current.value, end=" ")
            current = current.next_node
        print()
        
lc = LRUCache(10)
for i in range(10):
    lc.put(i + 1, i + 1)
lc.print_linked_list()
lc.put(11, 11)
lc.put(12, 12)
lc.put(5, 20000000)
lc.print_linked_list()
print(lc.get(1))
print(lc.get(3))
lc.print_linked_list()
# print(lc.bottom)
lc.put(14, 14)
lc.put(1, 1)
print(lc.get(8))
print(lc.get(7))
lc.print_linked_list()

10 9 8 7 6 5 4 3 2 1 
20000000 12 11 10 9 8 7 6 4 3 
None
3
3 20000000 12 11 10 9 8 7 6 4 
8
7
7 8 1 14 3 20000000 12 11 10 9 
